config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#index'
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def new
    @cat = Cat.new
  end

  def index
    @cats = Cat.all.order('name')
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_path(@cat)
    else
      render :new
    end
  end

  def update
    cat = Cat.find(params[:id])
    if cat.update(cat_params)
      redirect_to cat
    else
      render 'edit'
    end
  end

  def destroy
    Cat.find(params[:id]).destroy

    redirect_to cats_path
  end

end

private
  def cat_params
    params.require(:cat).permit(:name, :breed)
  end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/cats/_form.html.erb
<%= form_with model: @cat, local: true do |f| %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :breed, placeholder: "Breed" %>
  <%= f.submit "Save changes"%>
<% end %>

app/views/cats/edit.html.erb
<h2>Edit this kitty:</h2>

<%= render 'form' %>


<%= link_to "Home", cats_path %>

app/views/cats/index.html.erb
<h1>Welcome to CATalog!</h1>
<p><%= link_to 'Make a new cat!', new_cat_path %> </p>
<ol>
<% @cats.each do |cat| %>
  <li><%= link_to cat.name, cat_path(cat)%></li>
<% end %>
</ol>

app/views/cats/new.html.erb
<h2>Give your cat a name and a breed <3</h2>
<h3>(Give it a nice name!)</h3>

<%= render 'form' %>

<%= link_to 'Go back', cats_path %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<h2>Breed: <%= @cat.breed %></h2>
<ul>
  <li><%= link_to "Edit", edit_cat_path %></li>
  <li><%= link_to 'Delete', cat_path,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></li>
</ul>
<%= link_to "All Cats", cats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/root/index.html.erb
<center>
  <h1>Our Incredible App About Cats!</h1>
  <h2><%= link_to "See All Cats", cats_path%></h2>
</center>